------------------------------------------------------------------------------------------------------------------
-- File  : Labs_RWC23_0_creaDB.sql
-- Goal  : Full end-to-end Oracle setup for an "Ultra Realistic ++" dataset
--         based on Rugby World Cup 2023 (France): schema + data loading.
--
-- Notes :
--  - Designed for Oracle 26ai (IDENTITY columns, FETCH FIRST).
--  - Script is self-contained: it uses INSERTs + PL/SQL generators.
--  - Match results (scores/dates) align with the CSV you generated earlier.
--  - You can run this as one file in SQL*Plus, SQLcl, SQL Developer, etc.
--------------------------------------------------------------------------------


BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'RWC_TICKETS','RWC_FANS','RWC_POSTES','RWC_JOUEURS',
      'RWC_RESULTATS','RWC_MATCHS','RWC_MATCHS_STG',
      'RWC_EQUIPES','RWC_POULES','RWC_STADES','RWC_TOURNOIS','RWC_PAYS'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- Also recreate the rwc23 user cleanly
DROP USER rwc23 CASCADE;
CREATE USER rwc23 IDENTIFIED BY "Oracle123!";
GRANT ALL PRIVILEGES TO rwc23;


-- ================================================================
-- CREATE DATABASE OBJECTS FOR rwc23 USER
-- ================================================================
CONN rwc23@FREEPDB1

--------------------------------------------------------------------------------
-- 0) Optional session settings (readability / safety)
--------------------------------------------------------------------------------
-- SET DEFINE OFF;         -- Uncomment if you have issues with & substitution
-- ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
-- ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

--------------------------------------------------------------------------------
-- 1) DROP existing objects (idempotent script)
--    We drop in dependency order (children -> parents).
--------------------------------------------------------------------------------
BEGIN
  FOR t IN (
    SELECT table_name
    FROM user_tables
    WHERE table_name IN (
      'RWC_TICKETS',
	  'RWC_FANS',
      'RWC_POSTES',
	  'RWC_JOUEURS',
      'RWC_RESULTATS',
	  'RWC_MATCHS',
      'RWC_MATCHS_STG',
      'RWC_EQUIPES',
	  'RWC_POULES',
	  'RWC_STADES',
	  'RWC_TOURNOIS',
	  'RWC_PAYS'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS';
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN NULL; -- "Drop if exists" behavior
END;
/
-- Views (if they exist)
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_RWC_RESULTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_rwc_poules_TABLE_BASIC';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

--------------------------------------------------------------------------------
-- 2) Core reference tables (PAYS, TOURNOIS, POULES, EQUIPES, STADES)
--------------------------------------------------------------------------------

-- Countries participating in RWC 2023 (20 teams)
CREATE TABLE rwc_pays (
  id_pays			NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pays_iso_code		CHAR(3)			NOT NULL UNIQUE,
  pays_nom			VARCHAR2(80)	NOT NULL
);

-- Tournament header (host country, dates, edition year)
CREATE TABLE rwc_tournois (
  id_tournoi		NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournoi_lib		VARCHAR2(120)	NOT NULL,
  tournoi_dt_deb	DATE			NOT NULL,
  tournoi_dt_fin	DATE			NOT NULL,
  tournoi_edition	NUMBER(4)		NOT NULL,
  id_pays			NUMBER			NOT NULL REFERENCES rwc_pays(id_pays),
  CONSTRAINT rwc_tourn_dates_ck CHECK (tournoi_dt_fin >= tournoi_dt_deb)
);

-- Pools A-D (per tournament)
CREATE TABLE rwc_poules (
  id_poule			NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poule_code		CHAR(1)			NOT NULL,
  id_tournoi		NUMBER			NOT NULL REFERENCES rwc_tournois(id_tournoi),
  CONSTRAINT rwc_poules_uk UNIQUE (id_tournoi, poule_code),
  CONSTRAINT rwc_poules_code_ck CHECK (poule_code IN ('A','B','C','D'))
);

-- Teams (one per country per tournament; attached to a pool)
CREATE TABLE rwc_equipes (
  id_equipe			NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipe_lib		VARCHAR2(80)	NOT NULL,
  id_pays			NUMBER			NOT NULL REFERENCES rwc_pays(id_pays),
  id_tournoi		NUMBER			NOT NULL REFERENCES rwc_tournois(id_tournoi),
  id_poule			NUMBER			NOT NULL REFERENCES rwc_poules(id_poule),
  CONSTRAINT rwc_equipes_uk UNIQUE (id_tournoi, id_pays)
);

-- Venues (official host cities; match_ville is unique for simple mapping)
CREATE TABLE rwc_stades (
  id_stade			NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stade_ville		VARCHAR2(80)	NOT NULL UNIQUE,
  stade_lib			VARCHAR2(120)	NOT NULL,
  stade_capacite	NUMBER(7)		NOT NULL,
  id_tournoi		NUMBER			NOT NULL REFERENCES rwc_tournois(id_tournoi),
  CONSTRAINT rwc_stades_cap_ck CHECK (stade_capacite > 0)
);

--------------------------------------------------------------------------------
-- 3) Matches & results tables
--------------------------------------------------------------------------------

-- Matches (we store match_date for accuracy; match_kickoff kept nullable by design)
CREATE TABLE rwc_matchs (
  id_match			NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_tour		VARCHAR2(20)	NOT NULL CHECK (match_tour IN ('POOL','QF','SF','FINAL','BRONZE')),
  match_date		DATE			NOT NULL,
  match_kickoff		TIMESTAMP		NULL,
  match_code		VARCHAR2(30)	NOT NULL,
  match_recette		NUMBER(12,2)	NULL,
  id_tournoi		NUMBER			NOT NULL REFERENCES rwc_tournois(id_tournoi),
  id_stade			NUMBER			NOT NULL REFERENCES rwc_stades(id_stade),
  id_poule			NUMBER			NULL REFERENCES rwc_poules(id_poule),
  CONSTRAINT rwc_matchs_uk UNIQUE (id_tournoi, match_code)
);

-- Match results: two lines per match (HOME/AWAY)
CREATE TABLE rwc_resultats (
  id_resultat		NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resultat_side		VARCHAR2(4)		NOT NULL CHECK (resultat_side IN ('HOME','AWAY')),
  resultat_points	NUMBER(3)		NOT NULL,
  id_match			NUMBER			NOT NULL REFERENCES rwc_matchs(id_match) ON DELETE CASCADE,
  id_equipe			NUMBER			NOT NULL REFERENCES rwc_equipes(id_equipe),
  CONSTRAINT rwc_resultats_uk UNIQUE (id_match, resultat_side),
  CONSTRAINT rwc_resultats_uk2 UNIQUE (id_match, id_equipe)
);

-- Helpful indexes for the future exercises
CREATE INDEX ix_match_date			ON rwc_matchs(match_date);
CREATE INDEX ix_match_match_tour	ON rwc_matchs(match_tour);
CREATE INDEX ix_matchteam_mid		ON rwc_resultats(id_match);

--------------------------------------------------------------------------------
-- 4) People & commercial volume (players, squads, fans, tickets)
--------------------------------------------------------------------------------

-- Players are stored by nationality (id_pays). Names here are synthetic by default.
CREATE TABLE rwc_joueurs (
  id_joueur			NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pays			NUMBER			NOT NULL REFERENCES rwc_pays(id_pays),
  joueur_nom		VARCHAR2(120)	NOT NULL,
  joueur_dt_naiss	DATE
);

-- Squad membership for the tournament (one row per player per team + shirt number)
CREATE TABLE rwc_postes (
  id_poste			NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poste_num_maillot	NUMBER(2)		NOT NULL,
  poste_position_code VARCHAR2(3)	NOT NULL,
  id_equipe			NUMBER			NOT NULL REFERENCES rwc_equipes(id_equipe),
  id_joueur			NUMBER			NOT NULL REFERENCES rwc_joueurs(id_joueur),
  CONSTRAINT rwc_postes_uk UNIQUE (id_equipe, id_joueur),
  CONSTRAINT rwc_postes_num_uk UNIQUE (id_equipe, poste_num_maillot)
);

-- Fans
CREATE TABLE rwc_fans (
  id_fan			NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fan_nom			VARCHAR2(120)	NOT NULL,
  fan_email			VARCHAR2(200)	NOT NULL UNIQUE,
  fan_dt_crea		TIMESTAMP		DEFAULT SYSTIMESTAMP NOT NULL,
  id_pays			NUMBER			REFERENCES rwc_pays(id_pays)
);

-- Tickets (high-volume table for GROUP BY, joins, top-N, window functions, etc.)
CREATE TABLE rwc_tickets (
  id_ticket			NUMBER			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_cat		VARCHAR2(10)	NOT NULL CHECK (ticket_cat IN ('CAT1','CAT2','CAT3','VIP')),
  ticket_prix		NUMBER(7,2)		NOT NULL CHECK (ticket_prix > 0),
  ticket_dt_achat	TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  id_match			NUMBER			NOT NULL REFERENCES rwc_matchs(id_match) ON DELETE CASCADE,
  id_fan			NUMBER			NOT NULL REFERENCES rwc_fans(id_fan) ON DELETE CASCADE
);

CREATE INDEX ix_ticket_match ON rwc_tickets(id_match);
CREATE INDEX ix_ticket_fan   ON rwc_tickets(id_fan);

--------------------------------------------------------------------------------
-- 5) Staging table (clean ingest pattern)
--    Why staging? Because in real life you load data first (CSV), validate, then
--    promote into normalized tables. Here we keep it as INSERTs for self-containment.
--------------------------------------------------------------------------------
CREATE TABLE rwc_matchs_stg (
  match_code		VARCHAR2(30)	PRIMARY KEY,
  match_tour		VARCHAR2(20)	NOT NULL,
  poule_code		CHAR(1)			NULL,
  match_date		DATE			NOT NULL,
  match_ville		VARCHAR2(80)	NOT NULL,
  match_equipe_locale		VARCHAR2(80)	NOT NULL,
  match_equipe_visiteur		VARCHAR2(80)	NOT NULL,
  match_equipe_locale_pts	NUMBER(3)		NOT NULL,
  match_equipe_visiteur_pts	NUMBER(3)		NOT NULL,
  match_heure_kickoff		VARCHAR2(10)	NULL,		-- optional ("21:00")
  match_timezone	VARCHAR2(10)	NULL,				-- optional ("CEST")
  match_affluence	NUMBER			NULL,				-- optional
  match_arbitre		VARCHAR2(120)	NULL				-- optional
);

--------------------------------------------------------------------------------
-- 6) Load reference data
--------------------------------------------------------------------------------

-- 6.1 Countries (20)
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('FRA','France');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('RSA','South Africa');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('NZL','New Zealand');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('IRL','Ireland');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('SCO','Scotland');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('WAL','Wales');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('ENG','England');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('AUS','Australia');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('ARG','Argentina');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('JPN','Japan');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('FJI','Fiji');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('ITA','Italy');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('GEO','Georgia');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('SAM','Samoa');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('TON','Tonga');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('URU','Uruguay');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('NAM','Namibia');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('ROM','Romania');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('CHI','Chile');
INSERT INTO rwc_pays (pays_iso_code, pays_nom) VALUES ('POR','Portugal');
COMMIT;

-- 6.2 Tournament header (RWC 2023 hosted by France)
DECLARE
  v_fr NUMBER;
BEGIN
  SELECT id_pays INTO v_fr FROM rwc_pays WHERE pays_iso_code='FRA';
  INSERT INTO rwc_tournois(tournoi_lib, tournoi_dt_deb, tournoi_dt_fin, tournoi_edition, id_pays)
  VALUES ('Rugby World Cup 2023', DATE '2023-09-08', DATE '2023-10-28', 2023, v_fr);
END;
/
COMMIT;

-- 6.3 Pools A-D
DECLARE
  v_tid NUMBER;
BEGIN
  SELECT id_tournoi INTO v_tid FROM rwc_tournois WHERE tournoi_edition=2023;
  FOR p IN (SELECT 'A' c FROM dual UNION ALL SELECT 'B' FROM dual UNION ALL SELECT 'C' FROM dual UNION ALL SELECT 'D' FROM dual) LOOP
    INSERT INTO rwc_poules(id_tournoi, poule_code) VALUES (v_tid, p.c);
  END LOOP;
END;
/
COMMIT;

-- 6.4 Teams (official pool composition for RWC 2023)
-- 6.4 Teams (official pool composition for RWC 2023)
-- FIX: avoid using local PL/SQL functions inresultat_side SQL statements (PLS-00231).
DECLARE
  v_tid NUMBER;

  -- pool ids
  v_pool_a NUMBER;
  v_pool_b NUMBER;
  v_pool_c NUMBER;
  v_pool_d NUMBER;

  -- country ids
  v_fra NUMBER; v_rsa NUMBER; v_nzl NUMBER; v_irl NUMBER; v_sco NUMBER;
  v_wal NUMBER; v_eng NUMBER; v_aus NUMBER; v_arg NUMBER; v_jpn NUMBER;
  v_fji NUMBER; v_ita NUMBER; v_geo NUMBER; v_sam NUMBER; v_ton NUMBER;
  v_uru NUMBER; v_nam NUMBER; v_rom NUMBER; v_chi NUMBER; v_por NUMBER;
BEGIN
  SELECT id_tournoi INTO v_tid
  FROM rwc_tournois
  WHERE tournoi_edition=2023;

  -- pool ids
  SELECT id_poule INTO v_pool_a FROM rwc_poules WHERE id_tournoi=v_tid AND poule_code='A';
  SELECT id_poule INTO v_pool_b FROM rwc_poules WHERE id_tournoi=v_tid AND poule_code='B';
  SELECT id_poule INTO v_pool_c FROM rwc_poules WHERE id_tournoi=v_tid AND poule_code='C';
  SELECT id_poule INTO v_pool_d FROM rwc_poules WHERE id_tournoi=v_tid AND poule_code='D';

  -- country ids
  SELECT id_pays INTO v_fra FROM rwc_pays WHERE pays_iso_code='FRA';
  SELECT id_pays INTO v_rsa FROM rwc_pays WHERE pays_iso_code='RSA';
  SELECT id_pays INTO v_nzl FROM rwc_pays WHERE pays_iso_code='NZL';
  SELECT id_pays INTO v_irl FROM rwc_pays WHERE pays_iso_code='IRL';
  SELECT id_pays INTO v_sco FROM rwc_pays WHERE pays_iso_code='SCO';
  SELECT id_pays INTO v_wal FROM rwc_pays WHERE pays_iso_code='WAL';
  SELECT id_pays INTO v_eng FROM rwc_pays WHERE pays_iso_code='ENG';
  SELECT id_pays INTO v_aus FROM rwc_pays WHERE pays_iso_code='AUS';
  SELECT id_pays INTO v_arg FROM rwc_pays WHERE pays_iso_code='ARG';
  SELECT id_pays INTO v_jpn FROM rwc_pays WHERE pays_iso_code='JPN';
  SELECT id_pays INTO v_fji FROM rwc_pays WHERE pays_iso_code='FJI';
  SELECT id_pays INTO v_ita FROM rwc_pays WHERE pays_iso_code='ITA';
  SELECT id_pays INTO v_geo FROM rwc_pays WHERE pays_iso_code='GEO';
  SELECT id_pays INTO v_sam FROM rwc_pays WHERE pays_iso_code='SAM';
  SELECT id_pays INTO v_ton FROM rwc_pays WHERE pays_iso_code='TON';
  SELECT id_pays INTO v_uru FROM rwc_pays WHERE pays_iso_code='URU';
  SELECT id_pays INTO v_nam FROM rwc_pays WHERE pays_iso_code='NAM';
  SELECT id_pays INTO v_rom FROM rwc_pays WHERE pays_iso_code='ROM';
  SELECT id_pays INTO v_chi FROM rwc_pays WHERE pays_iso_code='CHI';
  SELECT id_pays INTO v_por FROM rwc_pays WHERE pays_iso_code='POR';

  -- Pool A: NZL, FRA, ITA, URU, NAM
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_nzl,v_tid,v_pool_a,'New Zealand');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_fra,v_tid,v_pool_a,'France');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_ita,v_tid,v_pool_a,'Italy');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_uru,v_tid,v_pool_a,'Uruguay');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_nam,v_tid,v_pool_a,'Namibia');

  -- Pool B: RSA, IRL, SCO, ROM, TON
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_rsa,v_tid,v_pool_b,'South Africa');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_irl,v_tid,v_pool_b,'Ireland');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_sco,v_tid,v_pool_b,'Scotland');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_rom,v_tid,v_pool_b,'Romania');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_ton,v_tid,v_pool_b,'Tonga');

  -- Pool C: WAL, AUS, FJI, GEO, POR
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_wal,v_tid,v_pool_c,'Wales');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_aus,v_tid,v_pool_c,'Australia');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_fji,v_tid,v_pool_c,'Fiji');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_geo,v_tid,v_pool_c,'Georgia');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_por,v_tid,v_pool_c,'Portugal');

  -- Pool D: ENG, JPN, ARG, SAM, CHI
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_eng,v_tid,v_pool_d,'England');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_jpn,v_tid,v_pool_d,'Japan');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_arg,v_tid,v_pool_d,'Argentina');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_sam,v_tid,v_pool_d,'Samoa');
  INSERT INTO rwc_equipes(id_pays,id_tournoi,id_poule,equipe_lib) VALUES (v_chi,v_tid,v_pool_d,'Chile');
END;
/
COMMIT;

-- 6.5 Venues (official host cities -> stadium name + stade_capacite)
DECLARE
  v_tid NUMBER;
BEGIN
  SELECT id_tournoi INTO v_tid FROM rwc_tournois WHERE tournoi_edition=2023;

  INSERT INTO rwc_stades(id_tournoi, stade_ville, stade_lib, stade_capacite) VALUES (v_tid,'Saint-Denis','Stade de France',80698);
  INSERT INTO rwc_stades(id_tournoi, stade_ville, stade_lib, stade_capacite) VALUES (v_tid,'Marseille','Stade Vélodrome',67394);
  INSERT INTO rwc_stades(id_tournoi, stade_ville, stade_lib, stade_capacite) VALUES (v_tid,'Décines-Charpieu','Parc OL',59186);
  INSERT INTO rwc_stades(id_tournoi, stade_ville, stade_lib, stade_capacite) VALUES (v_tid,'Villeneuve-d''Ascq','Stade Pierre-Mauroy',50186);
  INSERT INTO rwc_stades(id_tournoi, stade_ville, stade_lib, stade_capacite) VALUES (v_tid,'Bordeaux','Stade de Bordeaux',42115);
  INSERT INTO rwc_stades(id_tournoi, stade_ville, stade_lib, stade_capacite) VALUES (v_tid,'Saint-Étienne','Stade Geoffroy-Guichard',41965);
  INSERT INTO rwc_stades(id_tournoi, stade_ville, stade_lib, stade_capacite) VALUES (v_tid,'Nice','Allianz Riviera',35624);
  INSERT INTO rwc_stades(id_tournoi, stade_ville, stade_lib, stade_capacite) VALUES (v_tid,'Nantes','Stade de la Beaujoire',35322);
  INSERT INTO rwc_stades(id_tournoi, stade_ville, stade_lib, stade_capacite) VALUES (v_tid,'Toulouse','Stadium de Toulouse',33150);
END;
/
COMMIT;

--------------------------------------------------------------------------------
-- 7) Load match data into STAGING (48 matches)
--------------------------------------------------------------------------------

-- POOL A
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA01','POOL','A',DATE '2023-09-08','Saint-Denis','France','New Zealand',27,13);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA02','POOL','A',DATE '2023-09-09','Saint-Étienne','Italy','Namibia',52,8);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA03','POOL','A',DATE '2023-09-14','Villeneuve-d''Ascq','France','Uruguay',27,12);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA04','POOL','A',DATE '2023-09-15','Toulouse','New Zealand','Namibia',71,3);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA05','POOL','A',DATE '2023-09-20','Nice','Italy','Uruguay',38,17);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA06','POOL','A',DATE '2023-09-21','Marseille','France','Namibia',96,0);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA07','POOL','A',DATE '2023-09-27','Décines-Charpieu','Uruguay','Namibia',36,26);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA08','POOL','A',DATE '2023-09-29','Décines-Charpieu','New Zealand','Italy',96,17);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA09','POOL','A',DATE '2023-10-05','Décines-Charpieu','New Zealand','Uruguay',73,0);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PA10','POOL','A',DATE '2023-10-06','Décines-Charpieu','France','Italy',60,7);

-- POOL B
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB01','POOL','B',DATE '2023-09-09','Bordeaux','Ireland','Romania',82,8);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB02','POOL','B',DATE '2023-09-10','Marseille','South Africa','Scotland',18,3);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB03','POOL','B',DATE '2023-09-16','Nantes','Ireland','Tonga',59,16);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB04','POOL','B',DATE '2023-09-17','Bordeaux','South Africa','Romania',76,0);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB05','POOL','B',DATE '2023-09-23','Saint-Denis','South Africa','Ireland',8,13);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB06','POOL','B',DATE '2023-09-24','Nice','Scotland','Tonga',45,17);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB07','POOL','B',DATE '2023-09-30','Villeneuve-d''Ascq','Scotland','Romania',84,0);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB08','POOL','B',DATE '2023-10-01','Marseille','South Africa','Tonga',49,18);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB09','POOL','B',DATE '2023-10-07','Saint-Denis','Ireland','Scotland',36,14);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PB10','POOL','B',DATE '2023-10-08','Villeneuve-d''Ascq','Tonga','Romania',45,24);

-- POOL C
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC01','POOL','C',DATE '2023-09-09','Saint-Denis','Australia','Georgia',35,15);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC02','POOL','C',DATE '2023-09-10','Bordeaux','Wales','Fiji',32,26);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC03','POOL','C',DATE '2023-09-16','Nice','Wales','Portugal',28,8);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC04','POOL','C',DATE '2023-09-17','Saint-Étienne','Australia','Fiji',15,22);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC05','POOL','C',DATE '2023-09-23','Toulouse','Georgia','Portugal',18,18);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC06','POOL','C',DATE '2023-09-24','Décines-Charpieu','Wales','Australia',40,6);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC07','POOL','C',DATE '2023-09-30','Bordeaux','Fiji','Georgia',17,12);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC08','POOL','C',DATE '2023-10-01','Saint-Étienne','Australia','Portugal',34,14);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC09','POOL','C',DATE '2023-10-07','Nantes','Wales','Georgia',43,19);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PC10','POOL','C',DATE '2023-10-08','Toulouse','Fiji','Portugal',23,24);

-- POOL D
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD01','POOL','D',DATE '2023-09-09','Marseille','England','Argentina',27,10);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD02','POOL','D',DATE '2023-09-10','Toulouse','Japan','Chile',42,12);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD03','POOL','D',DATE '2023-09-16','Bordeaux','Samoa','Chile',43,10);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD04','POOL','D',DATE '2023-09-17','Nice','England','Japan',34,12);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD05','POOL','D',DATE '2023-09-22','Saint-Étienne','Argentina','Samoa',19,10);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD06','POOL','D',DATE '2023-09-23','Villeneuve-d''Ascq','England','Chile',71,0);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD07','POOL','D',DATE '2023-09-28','Toulouse','Japan','Samoa',28,22);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD08','POOL','D',DATE '2023-09-30','Nantes','Argentina','Chile',59,5);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD09','POOL','D',DATE '2023-10-07','Villeneuve-d''Ascq','England','Samoa',18,17);
INSERT INTO rwc_matchs_stg(match_code,match_tour,poule_code,match_date,match_ville,match_equipe_locale,match_equipe_visiteur,match_equipe_locale_pts,match_equipe_visiteur_pts) VALUES ('PD10','POOL','D',DATE '2023-10-08','Nantes','Japan','Argentina',27,39);

-- Knockout match_tour (+ optional meta)
INSERT INTO rwc_matchs_stg VALUES ('QF01','QF',NULL,DATE '2023-10-14','Marseille','Wales','Argentina',17,29,'17:00','CEST',62576,'Karl Dickson');
INSERT INTO rwc_matchs_stg VALUES ('QF02','QF',NULL,DATE '2023-10-14','Saint-Denis','Ireland','New Zealand',24,28,'21:00','CEST',78845,'Wayne Barnes');
INSERT INTO rwc_matchs_stg VALUES ('QF03','QF',NULL,DATE '2023-10-15','Marseille','England','Fiji',30,24,'17:00','CEST',61863,'Mathieu Raynal');
INSERT INTO rwc_matchs_stg VALUES ('QF04','QF',NULL,DATE '2023-10-15','Saint-Denis','France','South Africa',28,29,'21:00','CEST',79486,'Ben O''Keeffe');
INSERT INTO rwc_matchs_stg VALUES ('SF01','SF',NULL,DATE '2023-10-20','Saint-Denis','Argentina','New Zealand',6,44,'21:00','CEST',77653,'Angus Gardner');
INSERT INTO rwc_matchs_stg VALUES ('SF02','SF',NULL,DATE '2023-10-21','Saint-Denis','England','South Africa',15,16,'21:00','CEST',78098,'Ben O''Keeffe');
INSERT INTO rwc_matchs_stg VALUES ('BRONZE','BRONZE',NULL,DATE '2023-10-27','Saint-Denis','Argentina','England',23,26,'21:00','CEST',77674,'Nic Berry');
INSERT INTO rwc_matchs_stg VALUES ('FINAL','FINAL',NULL,DATE '2023-10-28','Saint-Denis','New Zealand','South Africa',11,12,'21:00','CEST',80065,'Wayne Barnes');

COMMIT;

--------------------------------------------------------------------------------
-- 8) Promote staging -> normalized match tables
-- FIX: avoid calling local PL/SQL functions from SQL (PLS-00231).
--------------------------------------------------------------------------------
DECLARE
  v_tid     NUMBER;

  v_mid     NUMBER;
  v_venue   NUMBER;
  v_pool    NUMBER;
  v_home    NUMBER;
  v_away    NUMBER;

  v_kick_ts TIMESTAMP;
BEGIN
  SELECT id_tournoi INTO v_tid
  FROM rwc_tournois
  WHERE tournoi_edition = 2023;

  FOR r IN (SELECT * FROM rwc_matchs_stg ORDER BY match_date, match_code) LOOP

    --------------------------------------------------------------------------
    -- 1) Resolve lookup keys -> surrogate keys (IDs)
    --------------------------------------------------------------------------

    -- Venue from match_ville
    SELECT id_stade INTO v_venue
    FROM rwc_stades
    WHERE stade_ville = r.match_ville;

    -- Pool from poule_code (nullable for knockout)
    IF r.poule_code IS NOT NULL THEN
      SELECT id_poule INTO v_pool
      FROM rwc_poules
      WHERE id_tournoi = v_tid
        AND poule_code = r.poule_code;
    ELSE
      v_pool := NULL;
    END IF;

    -- Teams from names
    SELECT id_equipe INTO v_home
    FROM rwc_equipes
    WHERE id_tournoi = v_tid
      AND equipe_lib = r.match_equipe_locale;

    SELECT id_equipe INTO v_away
    FROM rwc_equipes
    WHERE id_tournoi = v_tid
      AND equipe_lib = r.match_equipe_visiteur;

    --------------------------------------------------------------------------
    -- 2) Build kickoff timestamp only when provided (no guessing)
    --------------------------------------------------------------------------
    IF r.match_heure_kickoff IS NOT NULL THEN
      v_kick_ts := TO_TIMESTAMP(
        TO_CHAR(r.match_date,'YYYY-MM-DD') || ' ' || r.match_heure_kickoff,
        'YYYY-MM-DD HH24:MI'
      );
    ELSE
      v_kick_ts := NULL;
    END IF;

    --------------------------------------------------------------------------
    -- 3) Insert match + the 2 result lines (HOME / AWAY)
    --------------------------------------------------------------------------
    INSERT INTO rwc_matchs(id_tournoi, id_stade, match_tour, id_poule, match_date, match_kickoff, match_code)
    VALUES (v_tid, v_venue, r.match_tour, v_pool, r.match_date, v_kick_ts, r.match_code)
    RETURNING id_match INTO v_mid;

    INSERT INTO rwc_resultats(id_match, id_equipe, resultat_side, resultat_points)
    VALUES (v_mid, v_home, 'HOME', r.match_equipe_locale_pts);

    INSERT INTO rwc_resultats(id_match, id_equipe, resultat_side, resultat_points)
    VALUES (v_mid, v_away, 'AWAY', r.match_equipe_visiteur_pts);

  END LOOP;
END;
/
COMMIT;

--------------------------------------------------------------------------------
-- 9) Generate volume data: players, squads, fans, tickets
--------------------------------------------------------------------------------

-- Players + squads: 35 per team
DECLARE
  CURSOR c_team IS SELECT id_equipe, id_pays FROM rwc_equipes;
  v_pid NUMBER;
BEGIN
  FOR tm IN c_team LOOP
    FOR i IN 1..35 LOOP
      INSERT INTO rwc_joueurs(id_pays, joueur_nom, joueur_dt_naiss)
      VALUES (
        tm.id_pays,
        'Player '||tm.id_equipe||'-'||LPAD(i,2,'0'),
        DATE '1988-01-01' + TRUNC(DBMS_RANDOM.VALUE(0, 5000))
      )
      RETURNING id_joueur INTO v_pid;

      INSERT INTO rwc_postes(id_equipe, id_joueur, poste_num_maillot, poste_position_code)
      VALUES (
        tm.id_equipe,
        v_pid,
        i,
        CASE
          WHEN i = 1 THEN 'LH'
          WHEN i = 2 THEN 'HK'
          WHEN i = 3 THEN 'TH'
          WHEN i IN (4,5) THEN 'LK'
          WHEN i IN (6,7) THEN 'FL'
          WHEN i = 8 THEN 'N8'
          WHEN i = 9 THEN 'SH'
          WHEN i = 10 THEN 'FH'
          WHEN i = 11 THEN 'LC'
          WHEN i = 12 THEN 'IC'
          WHEN i = 13 THEN 'RW'
          WHEN i = 14 THEN 'LW'
          WHEN i = 15 THEN 'FB'
          ELSE 'RES'
        END
      );
    END LOOP;
  END LOOP;
END;
/
COMMIT;

-- Fans: 1000
DECLARE
BEGIN
  FOR i IN 1..1000 LOOP
    INSERT INTO rwc_fans(id_pays, fan_nom, fan_email)
    VALUES (
      (SELECT id_pays FROM rwc_pays ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY),
      'Fan '||LPAD(i,5,'0'),
      'fan'||LPAD(i,5,'0')||'@example.org'
    );
  END LOOP;
END;
/
COMMIT;

-- Tickets: 10000
DECLARE
BEGIN
  FOR i IN 1..10000 LOOP
    INSERT INTO rwc_tickets(id_match, id_fan, ticket_cat, ticket_prix)
    VALUES (
      (SELECT id_match FROM rwc_matchs ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY),
      (SELECT id_fan   FROM rwc_fans   ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY),
      CASE
        WHEN MOD(i,25)=0 THEN 'VIP'
        WHEN MOD(i,3)=0  THEN 'CAT1'
        WHEN MOD(i,3)=1  THEN 'CAT2'
        ELSE 'CAT3'
      END,
      CASE
        WHEN MOD(i,25)=0 THEN 500
        WHEN MOD(i,3)=0  THEN 180
        WHEN MOD(i,3)=1  THEN 120
        ELSE 70
      END
    );
  END LOOP;
END;
/
COMMIT;

--------------------------------------------------------------------------------
-- 11) Sanity checks (run manually)
--------------------------------------------------------------------------------
/*
SELECT * FROM rwc_tickets;
SELECT * FROM rwc_fans;
SELECT * FROM rwc_postes;
SELECT * FROM rwc_joueurs;
SELECT * FROM rwc_resultats;
SELECT * FROM rwc_matchs;
SELECT * FROM rwc_matchs_stg;
SELECT * FROM rwc_equipes;
SELECT * FROM rwc_poules;
SELECT * FROM rwc_stades;
SELECT * FROM rwc_tournois;
SELECT * FROM rwc_pays;

SELECT COUNT(*) AS matches_loaded FROM rwc_matchs;         -- Expect: 48
SELECT * FROM vw_rwc_results WHERE match_code='FINAL';   -- Final score
SELECT * FROM vw_rwc_results WHERE poule_code='A' ORDER BY match_date, match_code;
SELECT * FROM vw_rwc_poules_table_basic ORDER BY poule_code, table_resultat_points_basic DESC, resultat_points_diff DESC;
SELECT COUNT(*) AS players FROM rwc_joueurs;             -- Expect: 700
SELECT COUNT(*) AS fans    FROM rwc_fans;                -- Expect: 1000
SELECT COUNT(*) AS tickets FROM rwc_tickets;             -- Expect: 10000
*/
--------------------------------------------------------------------------------
