upstream thread_api {
    server thread-api:8080;
}

upstream tailor_panel {
    server tailor-panel:80;
}

upstream fabric_watch {
    server fabric-watch:3000;
}

server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/ssl/certs/server.crt;
    ssl_certificate_key /etc/ssl/private/server.key;
    ssl_protocols       TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # ModSecurity activé — OWASP CRS
    modsecurity on;
    modsecurity_rules_file /etc/modsecurity.d/include.conf;

    # thread-api (API mobile)
    location /api/ {
        proxy_pass http://thread_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health {
        proxy_pass http://thread_api;
    }

    # tailor-panel (back-office)
    location /panel/ {
        proxy_pass http://tailor_panel/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # fabric-watch (Grafana)
    location /grafana/ {
        proxy_pass http://fabric_watch/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
